name: train-deploy

on: 
  push:
  workflow_dispatch:
    inputs:
      GROUP:
        default: "rg-contoso-819prod"
      LOCATION:
        default: "eastus"
      WORKSPACE:
        default: "mlw-contoso-819prod"
    secrets:
      AZ_CREDS: ${{ secrets.AZ_CREDS }}

jobs:
  train-job:
    uses: ./.github/workflows/create-job.yml
    with: 
      GROUP: "rg-contoso-819prod"
      LOCATION: "eastus"
      WORKSPACE: "mlw-contoso-819prod"
