name: train-deploy

on: 
  push:
  workflow_dispatch:
    inputs:
      GROUP:
        default: "rg-contoso-819prod"
      LOCATION:
        default: "eastus"
      WORKSPACE:
        default: "mlw-contoso-819prod"


jobs:
  train-job:
#    environment: 
#      name: dev
#      url: ${{ steps.create-job-step.outputs.RUNURI }}
    uses: ./.github/workflows/create-job.yml
    with: 
      GROUP: "rg-contoso-819prod"
      LOCATION: "eastus"
      WORKSPACE: "mlw-contoso-819prod"
    secrets:
      AZ_CREDS: ${{ secrets.AZ_CREDS }}
  register-model-job:
    needs: train-job
    uses: ./.github/workflows/create-model-from-job.yml
    with: 
      GROUP: "rg-contoso-819prod"
      LOCATION: "eastus"
      WORKSPACE: "mlw-contoso-819prod"
      TRAININGJOB_RUNID: ${{ needs.train-job.outputs.MLJOB_RUNID }}
    secrets:
      AZ_CREDS: ${{ secrets.AZ_CREDS }}


