name: train-deploy

on: 
  push:
  workflow_dispatch:
    inputs:
      GROUP:
        default: "rg-contoso-819prod"
      LOCATION:
        default: "eastus"
      WORKSPACE:
        default: "mlw-contoso-819prod"

jobs:
  train-job:
    uses: ManojBableshwar/AzureMLOpsDemo/.github/workflows/create-job.yml@v1
    with: 
      GROUP: "rg-contoso-819prod"
      LOCATION: "eastus"
      WORKSPACE: "mlw-contoso-819prod"
