# unable to use reusable workflows due to a bug... see inline for bug details...
name: train-deploy

on: 
#  push:
  workflow_dispatch:
    inputs:
      GROUP:
        default: "rg-contoso-819prod"
      LOCATION:
        default: "eastus"
      WORKSPACE:
        default: "mlw-contoso-819prod"


jobs:
  train-job:
    uses: ./.github/workflows/create-job.yml
    with: 
      GROUP: "rg-contoso-819prod"
      LOCATION: "eastus"
      WORKSPACE: "mlw-contoso-819prod"
    secrets:
      AZ_CREDS: ${{ secrets.AZ_CREDS }}
  register-model-job:
    needs: train-job
    uses: ./.github/workflows/create-model.yml
    with: 
      GROUP: "rg-contoso-819prod"
      LOCATION: "eastus"
      WORKSPACE: "mlw-contoso-819prod"
# unbale to use reusable workflows becuase MLJOB_RUNID from train-job is not being passed to register-model-job
      TRAININGJOB_RUNID: ${{ needs.train-job.outputs.MLJOB_RUNID }}
    secrets:
      AZ_CREDS: ${{ secrets.AZ_CREDS }}


