name: xws-train-deploy-register-workflow


on: 
  workflow_dispatch:
    inputs:
      DEV_SUBSCRIPTION:
        default: "21d8f407-c4c4-452e-87a4-e609bfb86248"
      DEV_GROUP:
        default: "OpenDatasetsPMRG"
      DEV_LOCATION:
        default: "eastus2"
      DEV_WORKSPACE:
        default: "OpenDatasetsPMWorkspace"
      TEST_SUBSCRIPTION:
        default: "21d8f407-c4c4-452e-87a4-e609bfb86248"
      PROD_GROUP:
        default: "rg-contoso-819prod"
      PROD_LOCATION:
        default: "eastus"
      PROD_WORKSPACE:
        default: "mlw-contoso-819prod"
      TRAINING_COMPUTE:
        default: "azureml:cpu-cluster"
      AZUREML_REGISTRY:
        default: "ContosoMgSep22"

env:
  AZURE_ML_CLI_PRIVATE_FEATURES_ENABLED: true
  DEV_SUBSCRIPTION: ${{ inputs.DEV_SUBSCRIPTION }}
  DEV_GROUP: ${{ inputs.DEV_GROUP }}
  DEV_LOCATION: ${{ inputs.DEV_LOCATION }}
  DEV_WORKSPACE: ${{ inputs.DEV_WORKSPACE }}  
  TEST_SUBSCRIPTION: ${{ inputs.TEST_SUBSCRIPTION }}
  PROD_GROUP: ${{ inputs.PROD_GROUP }}
  PROD_LOCATION: ${{ inputs.PROD_LOCATION }}
  PROD_WORKSPACE: ${{ inputs.PROD_WORKSPACE }}  
  AZUREML_REGISTRY:  ${{ inputs.AZUREML_REGISTRY }}  

jobs:
  train-job:
    environment: 
      name: dev
      url: ${{ steps.create-job-step.outputs.RUNURI }}
    runs-on: ubuntu-18.04
    steps:
    - name: check-out-repo-step
      uses: actions/checkout@v2
    - name: azure-login-step
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZ_CREDS_CONTOSO_MLOPS }}
    - name: set-azureml-ws-context-step
      run: bash setup.sh 
      working-directory: cli
    - name: create-job-step
      id: create-job-step 
      run: bash -x cli/create-job.sh src/pipeline/pipeline.yml ${{ inputs.TRAINING_COMPUTE }} ${{ inputs.DEV_GROUP }} ${{ inputs.DEV_WORKSPACE }}
    outputs:
      TRAININGJOB_RUNID: ${{ steps.create-job-step.outputs.RUNID }}

  register-model-job:
    needs: train-job
    environment: 
      name: test
      url: ${{ steps.create-model-step.outputs.MODELURI }}
    runs-on: ubuntu-18.04
    steps:
    - name: check-out-repo-step
      uses: actions/checkout@v2
    - name: azure-login-step
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZ_CREDS_CONTOSO_MLOPS }}
    - name: set-azureml-ws-context-step
      run: bash setup.sh 
      working-directory: cli
    - name: create-model-step
      id: create-model-step
      run: bash -x cli/create-model.sh ${{ needs.train-job.outputs.TRAININGJOB_RUNID }} 2 taxi ${{ inputs.DEV_GROUP }} ${{ inputs.DEV_WORKSPACE }} ${{ inputs.AZUREML_REGISTRY }}
    outputs:
      CREATEMODELJOB_MODELID: ${{ steps.create-model-step.outputs.MODELID }}  
      CREATEMODELJOB_MODEL_REG_ID: ${{ steps.create-model-step.outputs.MODEL_REG_ID }} 
          

  deploy-model-job:
    needs: register-model-job
    environment: 
      name: pre-prod
      url: ${{ steps.deploy-model-step.outputs.EPURI }}
    runs-on: ubuntu-18.04
    steps:
    - name: check-out-repo-step
      uses: actions/checkout@v2
    - name: azure-login-step
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZ_CREDS_CONTOSO_MLOPS }}
    - name: set-azureml-ws-context-step
      run: bash setup.sh 
      working-directory: cli
    - name: deploy-model-step
      id: deploy-model-step
      run: bash -x cli/deploy-model.sh ${{ needs.register-model-job.outputs.CREATEMODELJOB_MODELID }} 1 ${{ needs.register-model-job.outputs.CREATEMODELJOB_MODEL_REG_ID }} ${{ inputs.PROD_GROUP }} ${{ inputs.PROD_WORKSPACE }} 
    outputs:
      DEPLOYJOB_ENDPOINTID: ${{ steps.deploy-model-step.outputs.ENDPOINTID }}
      DEPLOYJOB_DEPLOYMENTID: ${{ steps.deploy-model-step.outputs.DEPLOYMENTID }}
      DEPLOYJOB_EPURI: ${{ steps.deploy-model-step.outputs.EPURI }}

  release-model-job:
    needs: deploy-model-job
    environment: 
      name: prod
      url: ${{ needs.register-model-job.outputs.DEPLOYJOB_EPURI }}
    runs-on: ubuntu-18.04
    steps:
    - name: check-out-repo-step
      uses: actions/checkout@v2
    - name: azure-login-step
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZ_CREDS_CONTOSO_MLOPS }}
    - name: set-azureml-ws-context-step
      run: bash setup.sh 
      working-directory: cli
    - name: release-model-step
      id: release-model-step
      run: bash -x cli/release-model.sh ${{ needs.deploy-model-job.outputs.DEPLOYJOB_ENDPOINTID }} ${{ needs.deploy-model-job.outputs.DEPLOYJOB_DEPLOYMENTID }} ${{ inputs.PROD_GROUP }} ${{ inputs.PROD_WORKSPACE }} 

