name: train-deploy-register-workflow
on: 
  push:
  workflow_dispatch:
    inputs:
      GROUP:
        default: "rg-contoso-819prod"
      LOCATION:
        default: "eastus"
      WORKSPACE:
        default: "mlw-contoso-819prod"
  workflow_call:
    inputs:
      GROUP:
        default: "rg-contoso-819prod"
        type: string
      LOCATION:
        default: "eastus"
        type: string
      WORKSPACE:
        default: "mlw-contoso-819prod"
        type: string
    secrets:
      AZ_CREDS:
        required: true

env:
  GROUP: ${{ github.event.inputs.name.GROUP }}
  LOCATION: ${{ github.event.inputs.name.LOCATION }}
  WORKSPACE: ${{ github.event.inputs.name.WORKSPACE }}  

jobs:
  train-job:
    environment: 
      name: dev
      url: ${{ steps.create-job-step.outputs.RUNURI }}
    runs-on: ubuntu-latest
    steps:
    - name: check out repo
      uses: actions/checkout@v2
    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZ_CREDS}}
    - name: setup
      run: bash setup.sh 
      working-directory: cli
    - name: create-job-step
      id: create-job-step 
      run: bash -x cli/create-job.sh src/pipeline/pipeline.yml
    outputs:
      TRAININGJOB_RUNID: ${{ steps.create-job-step.outputs.RUNID }}
  register-model-job:
    environment: 
      name: test
      url: ${{ steps.create-model-step.outputs.MODELURI }}
    runs-on: ubuntu-latest
    steps:
    - name: check out repo
      uses: actions/checkout@v2
    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZ_CREDS}}
    - name: setup
      run: bash setup.sh 
      working-directory: cli
    - name: create-model-step
      id: create-model-step
      run: bash -x cli/create-model.sh ${{ needs.train-job.outputs.TRAININGJOB_RUNID }}  

